ALTER TABLE "Comic" RENAME COLUMN "title" TO "name";
ALTER TABLE "Comic" RENAME COLUMN "penciler" TO "pencils";
ALTER TABLE "Comic" RENAME COLUMN "currentPrice" TO "averagePrice";

ALTER TABLE "Comic" ALTER COLUMN "name" DROP NOT NULL;
ALTER TABLE "Comic" ALTER COLUMN "pricePaid" DROP NOT NULL;
ALTER TABLE "Comic" ALTER COLUMN "pricePaid" DROP DEFAULT;
ALTER TABLE "Comic" ALTER COLUMN "averagePrice" DROP NOT NULL;
ALTER TABLE "Comic" ALTER COLUMN "averagePrice" DROP DEFAULT;

ALTER TABLE "Comic" DROP COLUMN IF EXISTS "coverUrl";
ALTER TABLE "Comic" DROP COLUMN IF EXISTS "source";
ALTER TABLE "Comic" DROP COLUMN IF EXISTS "sourceId";

ALTER TABLE "Comic" ADD COLUMN IF NOT EXISTS "number" TEXT;
ALTER TABLE "Comic" ADD COLUMN IF NOT EXISTS "date" TEXT;
ALTER TABLE "Comic" ADD COLUMN IF NOT EXISTS "volume" TEXT;
ALTER TABLE "Comic" ADD COLUMN IF NOT EXISTS "direct" TEXT;
ALTER TABLE "Comic" ADD COLUMN IF NOT EXISTS "publisher" TEXT;
ALTER TABLE "Comic" ADD COLUMN IF NOT EXISTS "numberOfBooks" TEXT;
ALTER TABLE "Comic" ADD COLUMN IF NOT EXISTS "print" TEXT;
ALTER TABLE "Comic" ADD COLUMN IF NOT EXISTS "cover" TEXT;
ALTER TABLE "Comic" ADD COLUMN IF NOT EXISTS "variant" TEXT;
ALTER TABLE "Comic" ADD COLUMN IF NOT EXISTS "coverArtist" TEXT;
ALTER TABLE "Comic" ADD COLUMN IF NOT EXISTS "pointOfPurchase" TEXT;
ALTER TABLE "Comic" ADD COLUMN IF NOT EXISTS "signed" TEXT;
ALTER TABLE "Comic" ADD COLUMN IF NOT EXISTS "remarked" TEXT;
ALTER TABLE "Comic" ADD COLUMN IF NOT EXISTS "notes" TEXT;

DROP INDEX IF EXISTS "Comic_userId_title_idx";
CREATE INDEX IF NOT EXISTS "Comic_userId_name_idx" ON "Comic"("userId", "name");
